deployment:
  tasks:
    - export DEPLOYPATH=/home/crewryhvlt/admin.crewtrent.in
    - /usr/local/cpanel/3rdparty/bin/git pull origin master
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan optimize:clear
    - php artisan optimize
    - php artisan storage:link
