<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $quotation->code }} - Quotation</title>
    <style>
      body{font-family: DejaVu Sans, Arial, sans-serif; font-size:12px; color:#222;}
      .header{display:flex; justify-content:space-between; align-items:center;}
      .company {text-align:left;}
      .company img{height:60px;}
      .client {text-align:right;}
      table {width:100%; border-collapse:collapse; margin-top:20px;}
      th, td {padding:8px; border:1px solid #e1e1e1;}
      th {background:#f7f7f7; text-align:left;}
      .right {text-align:right;}
      .total-row td {font-weight:bold;}
      .notes {margin-top:20px; font-size:11px;}
      .footer {position:fixed; bottom:20px; font-size:10px; width:100%; text-align:center; color:#888;}
    </style>
</head>
<body>
  <div class="header">
    <div class="company">
      <img src="{{ public_path('images/crewrent-logo.png') }}" alt="logo" />
      <div><strong>Crewrent Enterprises</strong></div>
      <div>Address line, City</div>
      <div>Phone: +91-XXXXXXXXXX | Email: info@crewrent.com</div>
    </div>
    <div class="client">
      <h2>Quotation</h2>
      <div><strong>{{ $quotation->code }}</strong></div>
      <div>Date: {{ $quotation->created_at->format('d M Y') }}</div>
      <div>To: <strong>{{ $quotation->client_name }}</strong></div>
      <div>{{ $quotation->client_email }}</div>
      <div>{{ $quotation->client_phone }}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Description</th>
        <th>Type</th>
        <th class="right">Qty</th>
        <th class="right">Unit Price</th>
        <th class="right">Tax %</th>
        <th class="right">Total</th>
      </tr>
    </thead>
    <tbody>
      @foreach($quotation->items as $i => $item)
      <tr>
        <td>{{ $i+1 }}</td>
        <td>
          <strong>{{ $item->item_name }}</strong><br>
          <div style="font-size:11px; color:#555;">{{ $item->description }}</div>
        </td>
        <td>{{ $item->item_type }}</td>
        <td class="right">{{ $item->quantity }}</td>
        <td class="right">{{ number_format($item->unit_price,2) }}</td>
        <td class="right">{{ $item->tax_percent ?? 0 }}</td>
        <td class="right">{{ number_format($item->total_price,2) }}</td>
      </tr>
      @endforeach
    </tbody>
    <tfoot>
      <tr class="total-row">
        <td colspan="6" class="right">Subtotal</td>
        <td class="right">{{ number_format($quotation->subtotal,2) }}</td>
      </tr>
      <tr class="total-row">
        <td colspan="6" class="right">Tax</td>
        <td class="right">{{ number_format($quotation->tax_amount,2) }}</td>
      </tr>
      <tr class="total-row">
        <td colspan="6" class="right">Discount</td>
        <td class="right">- {{ number_format($quotation->discount_amount,2) }}</td>
      </tr>
      <tr class="total-row">
        <td colspan="6" class="right">Total</td>
        <td class="right">{{ number_format($quotation->total_amount,2) }}</td>
      </tr>
    </tfoot>
  </table>

  <div class="notes">
    <strong>Notes & Terms:</strong>
    <div>
      {!! nl2br(e($quotation->notes ?: "1) Security deposit applicable as per policy.\n2) 50% advance required to confirm booking. Balance at dispatch.\n3) Quote valid for 7 days.\n4) Equipment must be returned in same condition.")) !!}
    </div>
  </div>

  <div class="footer">
    This quotation is computer generated by Crewrent Enterprises.
  </div>
</body>
</html>
